export enum CalendarEntryType {
  vacation = 'vacation',
  plannedVacation = 'planned vacation',
  halfDayVacation = 'half-day vacation',
  unpaidLeave = 'unpaid leave',
  parentalLeave = 'parental leave',
  bereavement = 'bereavement',
  otherVacation = 'other vacation',
  sickLeave = 'sick leave',
  homeOffice = 'home office',
  workAtOffice = 'work at office',
  workAtClient = 'work at client',
  publicHoliday = 'public holiday',
  education = 'education',
  shift1 = 'shift 1',
  shift2 = 'shift 2',
  shift3 = 'shift 3',
  shift4 = 'shift 4',
  remove = 'REMOVE',
}
